fix

diff --git a/github/workflows/01-building-blocks.yml b/github/workflows/01-building-blocks.yml
--- a/github/workflows/01-building-blocks.yml
+++ b/github/workflows/01-building-blocks.yml
@@ -1,7 +1,8 @@
 # 01 - Building BLocks
 
-name: "01 - Building Blocks"
-on: push, workflow_dispatch
+name: 01 - Building Blocks
+
+on: push
 
 jobs:
   echo-hello:
@@ -13,5 +14,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
-        run: echo "I will fail"
-        run: echo "Goodbye!"
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Goodbye
+        run: echo "goodbye!"
